### ISSUE TITLE
get_credentials returns None for some users

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#140]
```
12/05/2013 16:11:11:INFO    :chapi:MA: amcanary@gpolab.bbn.com: Invoked get_credentials Options {} Arguments {'member_urn': 'urn:publicid:IDN+ch.geni.net+user+amcanary'}
12/05/2013 16:11:12:INFO    :chapi:MA: amcanary@gpolab.bbn.com: Result from get_credentials: [{'geni_value': None, 'geni_version': 1, 'geni_type': 'geni_sfa'}]
```

Some users are getting their credentials though

 _Imported from trac ticket [#140](http://trac.gpolab.bbn.com/chapi/ticket/140),  created by ahelsing on 12-05-2013 at 16:22, last modified: 12-09-2013 at 12:56_

**Comment by ahelsing** [comment]
At the very least, get_credentials should probably log an error or warning if it is failing to return a user credential, since this indicates that someone has a valid certificate as far as apache is concerned, but it is not one in our DB

_Trac comment by ahelsing on 12-05-2013 at 16:24_

**Comment by tcmitchell** [comment]
The other user (not amcanary) who had this problem was using a certificate that is no longer in our database. Because we don't find it in the database no user credential is returned. The logging for this is at debug level and should be upped to info or warn. The fix is for the user to download their current certificate.

_Trac comment by tmitchel (github user: tcmitchell) on 12-05-2013 at 16:58_

**Comment by tcmitchell** [comment]
I changed the log message to warn level. We should go deeper and not return a non-existent sfa-style user credential. It should be omitted from the set altogether. This change needs to be tested with PGCH to make sure the lack of an sfa-style credential doesn't cause errors there.

Reducing this to normal priority because we know the fix if any other users are affected.

_Trac comment by tmitchel (github user: tcmitchell) on 12-05-2013 at 17:14_
