### ISSUE TITLE
install_ch should install the python-sqlalchemy package rather than using easy_install

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#15]
Software installed into central directories on Ubuntu systems via easy_install is difficult to maintain.  Install the python sqlalchemy module by installing the python-sqlalchemy package via apt-get, rather than by using easy_install.

 _Imported from trac ticket [#15](http://trac.gpolab.bbn.com/chapi/ticket/15),  created by chaos on 11-08-2013 at 12:11, last modified: 11-15-2013 at 08:10_

**Comment by tcmitchell** [comment]
The version of SQLAlchemy available on Ubuntu 10.04 (0.5.8) is not compatible with the version used in the software. The SQLAlchemy version available via easy_install is 0.8.3. That is why SQLAlchemy is installed via `easy_install`.

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 12:21_

**Comment by tcmitchell** [comment]
Reopening because we should control the version number of sqlalchemy instead of just accepting whatever easy_install gives us.

Also, consider using `pip` (package `python-pip`) which replaces easy_install and provides an uninstall option.

_Trac comment by tmitchel (github user: tcmitchell) on 11-08-2013 at 15:36_

**Comment by tcmitchell** [comment]
Switched over to using `pip` so that installed files can be tracked. Additionally, set version number to 0.8.3 to control installed version of SQLAlchemy.

_Trac comment by tmitchel (github user: tcmitchell) on 11-13-2013 at 16:02_
