### ISSUE TITLE
disabled users can still be added/removed from projects/slices, and their SSH keys listed

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#215]
You can still add/remove a disabled user from a project/slice. And you can still list their public SSH keys.

This means that the public SSH keys for a disabled user can be added to resources, and they can access those resources.

At a very minimum, we should forbid listing the keys for a disabled user. I'd also like to forbid adding them to a project or slice.

 _Imported from trac ticket [#215](http://trac.gpolab.bbn.com/chapi/ticket/215),  created by ahelsing on 01-22-2014 at 15:45, last modified: 05-23-2014 at 12:27_

**Comment by ahelsing** [comment]
Perhaps though we want to allow this for operators and authorities. Not essential.


_Trac comment by ahelsing on 01-22-2014 at 16:08_

**Comment by ahelsing** [comment]
Most thing I _believe_ are properly guarded by the guards, when the _caller_ is disabled. But when the caller is different and the subject is disabled, I think we aren't doing the proper checks. Perhaps this can be done in the guards? We want to do this at least (maybe only) on methods that modify attributes of the member.

In the MA, we should disable for disabled users: update_member_info,
lookup_login_info, get_credentials, create_key, update_key, lookup_keys, create_certificate, authorize_client, add_member_privilege, add_member_attribute, remove_member_attribute

In the SA: get_credentials, modify_slice_membership, modify_project_membership, invite_member, resolve_pending_request

_Trac comment by ahelsing on 01-22-2014 at 16:19_

**Comment by MarshallBrinn** [comment]
I'll grab this. As Aaron points out, this can't really be done in the guards or MethodContext which only deal with the caller. 

Here's what I plan to do:

If you ask for any method to modify a disabled user or any list CONTAINING a disabled user (per Aaron's list below), it should fail.

If you ask for a list of members of slices or projects, disabled users should not appear AT ALL in the response (even for operators),

Should still be able to call get_public_member_info and get_identifying_member_info on disabled users (so that you can print log messages they wrote, e.g.)

The call to get SSH keys should exclude any disabled user from its response.

Need to make sure that enable users still works with any changes we make here.



_Trac comment by mbrinn (github user: MarshallBrinn) on 01-23-2014 at 09:57_

**Comment by MarshallBrinn** [comment]
What I intend to do is fix the most significant FUNCTIONAL problem which is that disabled users can log in to slivers (since their SSH keys are provided). I will make it so that lookup_keys returns only keys for enabled users. The other issues (of not being able to change the attributes of disabled users, their memberships) is lower priority and I will fix this in a later release.



_Trac comment by mbrinn (github user: MarshallBrinn) on 01-28-2014 at 10:47_

**Comment by MarshallBrinn** [comment]
The code to prevent returning SSH key info for disabled users is tested and checked in (branch tkt215_disabledkeys) and merged with develop. 

This should be ready for the next major release. The rest of this function should be placed at some later release.

- Marshall

_Trac comment by mbrinn (github user: MarshallBrinn) on 01-28-2014 at 13:39_

**Comment by ahelsing** [comment]
I have a disabled temp account that can still be bulk added to a project.  That is, when I do the bulk add it offers to add it to a project instead of suggesting that I email that user.

_Trac comment by sedwards (github user: seledwards) on 03-25-2014 at 15:25_

**Comment by MarshallBrinn** [comment]
Here's what we decided to do:

1. If a request for SSH keys for a disabled user is received, log the request but return no keys (act as though the URN was not on the list)

2. If a request to add a disabled member to a slice or member, log the request but don't add t hem (act as though the URN was not on the add_to_members list)

Tested and checked in.

_Trac comment by mbrinn (github user: MarshallBrinn) on 05-23-2014 at 12:27_
