### ISSUE TITLE
Bug report: SLICE lookup match SLICE_URN returns only 1 slice

### ISSUE THREAD

**Issue by wvdemeer** [GENI-NSF/geni-ch#393]
A SLICE lookup with a match option on SLICE_URN, returns a single slice if there are multiple slices (there can be multiple slices if there exist expired slices with the same name).
This single slice is a random matching slice as far as I can see, not the oldest, or the newest, or the non-expired. 
I would expect this call to return all slices with that URN instead.

Example request where it goes wrong for my account:

Request "lookup" call:
```json
[
"SLICE",
[
   {
      "geni_type": "geni_sfa",
      "geni_version": "3",
      "geni_value": "... credential removed because not relevant ..."
      }
   ],
{
   "match": {
                 "SLICE_URN": [
                        "urn:publicid:IDN+ch.geni.net:ipv6proxy+slice+dummy"
                        ]
                 }
   }
]
```

The reply is a single, expired slice, while there is also a non expired slice, and multiple other expired slices. the lookup_for_member SLICE call did return all slices.

**Comment by tcmitchell** [comment]
This isn't really a bug, the return value (dictionary of dictionaries) limits the result to a single instance for a give URN because the outer dictionary is keyed by URN. The jFed team and the GPO software team discussed options and determined that a reasonable improvement would be to return the most recent slice with the given URN.

The current behavior, prior to the fix, returns a seemingly random instance of a slice with the desired URN. Instead, we'll make the result deterministic. It will be the currently active (non-expired) instance if there is one, or the most recently expired instance if none is active.
