### ISSUE TITLE
incorrect project roles on Projects page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-ch#47]
I removed myself from a project on which I was the lead using the geni-remove-project-member script.  Once I was removed, I could no longer view the project so added myself back in using geni-add-project-member. I was put in as auditor, which is expected. When I go to the "Project" page for the project, the member who was an admin is now listed as lead and I'm listed as auditor, which is correct.

However if I go to the "Projects" page, I am still listed as Project Lead.

 _Imported from trac ticket [#47](http://trac.gpolab.bbn.com/chapi/ticket/47),  created by phelinek on 11-15-2013 at 10:24, last modified: 11-15-2013 at 16:02_

**Comment by tcmitchell** [comment]
The lead role and the project lead are two separate things, unfortunately. I suspect you are still listed as the project lead on the projects page because the column in the pa_project table was not updated when you were removed from the project. That's probably a bug in the SA when removing a project member.  It sounds like the privileges are updated correctly, however.

_Trac comment by tmitchel (github user: tcmitchell) on 11-15-2013 at 10:29_

**Comment by ahelsing** [comment]
I'm working on the privileges.  Not checked in yet but working correctly in my branch.  What's the difference between project lead and lead role?

_Trac comment by phelinek on 11-15-2013 at 10:39_

**Comment by ahelsing** [comment]
No difference between project lead and lead role - duplicated data in 2 places, and some code looks in one place, and some in another. So you (the SA) have to keep them in sync.

_Trac comment by ahelsing on 11-15-2013 at 10:42_

**Comment by ahelsing** [comment]
needed to update pa_project table when changing project lead

_Trac comment by phelinek on 11-15-2013 at 16:02_
