### ISSUE TITLE
omni listmyslices doesn't work with pgch

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-ch#53]
I created a slice on the portal and omni listmyslices reports zero slices for me.

 _Imported from trac ticket [#53](http://trac.gpolab.bbn.com/chapi/ticket/53),  created by tmitchel on 11-15-2013 at 16:14, last modified: 11-18-2013 at 11:26_

**Comment by tcmitchell** [comment]
I see the following in amsoil.log when I call listmyslices:
```
2013-11-15 16:51:14,900 [ERROR] - [pgchv1] [SERVER] SERVER_ERROR ('USER_CREDENTIAL')
2013-11-15 16:51:14,900 [ERROR] - [pgchv1] Traceback (most recent call last):
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 77, in Resolve
    result = self._delegate.Resolve(client_cert, args)
  File "/usr/share/geni-ch/chapi/AMsoil-gpo-0.3.2/src/plugins/pgch/PGCH.py", line 324, in Resolve
    user_gid = gid.GID(public_info['USER_CREDENTIAL'])
KeyError: 'USER_CREDENTIAL'
```

_Trac comment by tmitchel (github user: tcmitchell) on 11-15-2013 at 16:52_

**Comment by MarshallBrinn** [comment]
Two problems: 

First I think it is _GENI_USER_CREDENTIAL, not USER_CREDENTIAL.

Second, this is exactly what I was hoping to remove as part of the CHAPI lookup_public_member_info call. It would be better for PGCH to call get_credentials from the MA so that we don't need to return the user credential from public member info.



_Trac comment by mbrinn (github user: MarshallBrinn) on 11-16-2013 at 08:25_

**Comment by tcmitchell** [comment]
The credential turned out to be a red herring altogether (see issue #55). More importantly, the 'slices' part of the return value was missing. Unfortunately, 'slices' is not documented in the PG API as part of the return value, making it hard to know it should be there. omni listmyslices works now.

_Trac comment by tmitchel (github user: tcmitchell) on 11-18-2013 at 11:26_
