### ISSUE TITLE
Add UTDallas-IG to GENI portal

### ISSUE THREAD

**Issue by heididempsey** [GENI-NSF/geni-ch#575]
Installation and testing of UTDALLAS-IG is complete.  This is a US Ignite InstaGENI rack.  See http://groups.geni.net/geni/wiki/GENIRacksHome/InstageniRacks/Operators/UTDallas

**Comment by tcmitchell** [comment]
1. Information on [how to add an aggregate](https://github.com/GENI-NSF/geni-ch/wiki/Add-An-Aggregate) is on the wiki
2. The aggregate page has much of the info needed: http://groups.geni.net/geni/wiki/GeniAggregate/UTDallasInstaGENI
   1. The UI Type will be `ui_instageni_am`
   2. The UI Categories should probably be `"ui_prod_cat ui_compute_cat ui_stitchable_cat ui_federated_cat"`
3. The aggregate will need to be added to [geni-lib](https://bitbucket.org/barnstorm/geni-lib) in order to include it in the Jacks context
